/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/app/components/UI/AppButton.vue')['default']
    AppFooter: typeof import('./src/app/components/core/AppFooter.vue')['default']
    AppHeader: typeof import('./src/app/components/core/AppHeader.vue')['default']
    AuthExitButton: typeof import('./src/auth/components/AuthExitButton.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    IBiWhatsapp: typeof import('~icons/bi/whatsapp')['default']
    ICarbonEdit: typeof import('~icons/carbon/edit')['default']
    ICarbonPassword: typeof import('~icons/carbon/password')['default']
    IIcBaselinePhone: typeof import('~icons/ic/baseline-phone')['default']
    IJamTelegram: typeof import('~icons/jam/telegram')['default']
    IJamViber: typeof import('~icons/jam/viber')['default']
    IJamWhatsapp: typeof import('~icons/jam/whatsapp')['default']
    IMajesticonsEditPen2Line: typeof import('~icons/majesticons/edit-pen2-line')['default']
    IMajesticonsPlusLine: typeof import('~icons/majesticons/plus-line')['default']
    IMaterialSymbolsAlternateEmailRounded: typeof import('~icons/material-symbols/alternate-email-rounded')['default']
    IMaterialSymbolsCloseRounded: typeof import('~icons/material-symbols/close-rounded')['default']
    IMaterialSymbolsDeleteOutlineRounded: typeof import('~icons/material-symbols/delete-outline-rounded')['default']
    IMaterialSymbolsEdit: typeof import('~icons/material-symbols/edit')['default']
    IMaterialSymbolsPerson: typeof import('~icons/material-symbols/person')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ISvgSpinners270Ring: typeof import('~icons/svg-spinners/270-ring')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
