/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/app/components/UI/AppButton.vue')['default']
    AppFooter: typeof import('./src/app/components/core/AppFooter.vue')['default']
    AppHeader: typeof import('./src/app/components/core/AppHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    ICarbonPassword: typeof import('~icons/carbon/password')['default']
    IMaterialSymbolsAlternateEmailRounded: typeof import('~icons/material-symbols/alternate-email-rounded')['default']
    IMaterialSymbolsCloseRounded: typeof import('~icons/material-symbols/close-rounded')['default']
    IMaterialSymbolsPerson: typeof import('~icons/material-symbols/person')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ISvgSpinners270Ring: typeof import('~icons/svg-spinners/270-ring')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
